// Static demo mode (GitHub Pages): the app runs entirely from prebaked JSON
// fixtures under public/demo-data/, generated by
// backend/scripts/build_demo_fixtures.py against a live local backend.
export const IS_DEMO = import.meta.env.VITE_DEMO_MODE === 'true'

export interface DemoWeatherPreset {
  id: string
  label: string
  /** Exact WeatherInput the fixture was generated with; absent for "off". */
  input?: {
    temperature_f: number
    humidity_pct: number
    wind_speed_mph: number
    wind_direction_deg: number
  }
}

export interface DemoMatchup {
  id: string
  label: string
  batter_id: string
  pitcher_id: string
  team_id: string
  batting_team_id: string
  stadium_id: string
}

export interface DemoManifest {
  generated_at: string
  model_version: string | null
  calibrator_version: string | null
  matchups: DemoMatchup[]
  weather_presets: DemoWeatherPreset[]
  players: import('@/types').PlayerSummary[]
}
